<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class BankDeposit extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function (BankDeposit $bankDeposit) {
            $bankDeposit->transaction()->create(
                [
                    'sender_type' => User::class,
                    'sender_id' => $bankDeposit->user_id,
                    'amount' => $bankDeposit->amount,
                    'received_at' => Carbon::now(),
                    'signature' => \Str::random(5),
                ]
            );
        });
    }

    protected $fillable = ['deposit_number', 'deposit_date','bank_id', 'user_id', 'amount', 'image','type'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function distributor()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function transaction()
    {
        return $this->morphOne(DistributorTransaction::class, 'receiver');
    }

    public function bank()
    {
        return $this->belongsTo(Bank::class, 'bank_id')->withDefault(new Bank);
    }
}
